DATALOADER:
  ASPECT_RATIO_GROUPING: true
  NUM_WORKERS: 4
  SIZE_DIVISIBILITY: 32
DATASETS:
  NAME: ''
  TEST:
  - VG150_test
  TO_TEST: ''
  TRAIN:
  - VG150_train
  VAL:
  - VG150_val
DETECTED_SGG_DIR: .
DTYPE: float16
GLOVE_DIR: /home/maelic/glove
INPUT:
  BRIGHTNESS: 0.0
  CONTRAST: 0.0
  FLIP_PROB_TRAIN: 0.5
  HUE: 0.0
  MAX_SIZE_TEST: 1000
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MIN_SIZE_TRAIN: 600
  PADDING: false
  PIXEL_MEAN:
  - 102.9801
  - 115.9465
  - 122.7717
  PIXEL_STD:
  - 1.0
  - 1.0
  - 1.0
  SATURATION: 0.0
  TO_BGR255: true
  VERTICAL_FLIP_PROB_TRAIN: 0.0
METRIC_TO_TRACK: mR
MODEL:
  ATTRIBUTE_ON: false
  BACKBONE:
    EXTRA_CONFIG: ''
    FREEZE: false
    FREEZE_CONV_BODY_AT: 2
    NMS_THRESH: 0.7
    TYPE: R-101-FPN
  BOX_HEAD: true
  CLS_AGNOSTIC_BBOX_REG: false
  DEVICE: cuda
  FBNET:
    ARCH: default
    ARCH_DEF: ''
    BN_TYPE: bn
    DET_HEAD_BLOCKS: []
    DET_HEAD_LAST_SCALE: 1.0
    DET_HEAD_STRIDE: 0
    DW_CONV_SKIP_BN: true
    DW_CONV_SKIP_RELU: true
    KPTS_HEAD_BLOCKS: []
    KPTS_HEAD_LAST_SCALE: 0.0
    KPTS_HEAD_STRIDE: 0
    MASK_HEAD_BLOCKS: []
    MASK_HEAD_LAST_SCALE: 0.0
    MASK_HEAD_STRIDE: 0
    RPN_BN_TYPE: ''
    RPN_HEAD_BLOCKS: 0
    SCALE_FACTOR: 1.0
    WIDTH_DIVISOR: 1
  FLIP_AUG: false
  FPN:
    USE_GN: false
    USE_RELU: false
  GROUP_NORM:
    DIM_PER_GP: -1
    EPSILON: 1.0e-05
    NUM_GROUPS: 32
  MASK_ON: false
  META_ARCHITECTURE: GeneralizedRCNN
  PRETRAINED_DETECTOR_CKPT: checkpoints/VG150/Backbones/faster_rcnn/model_final.pth
  RELATION_ON: true
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    DEFORMABLE_GROUPS: 1
    NUM_GROUPS: 32
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STAGE_WITH_DCN:
    - false
    - false
    - false
    - false
    STEM_FUNC: StemWithFixedBatchNorm
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: false
    TRANS_FUNC: BottleneckWithFixedBatchNorm
    WIDTH_PER_GROUP: 8
    WITH_MODULATED_DCN: false
  RETINANET:
    ANCHOR_SIZES:
    - 32
    - 64
    - 128
    - 256
    - 512
    ANCHOR_STRIDES:
    - 8
    - 16
    - 32
    - 64
    - 128
    ASPECT_RATIOS:
    - 0.5
    - 1.0
    - 2.0
    BBOX_REG_BETA: 0.11
    BBOX_REG_WEIGHT: 4.0
    BG_IOU_THRESHOLD: 0.4
    FG_IOU_THRESHOLD: 0.5
    INFERENCE_TH: 0.05
    LOSS_ALPHA: 0.25
    LOSS_GAMMA: 2.0
    NMS_TH: 0.4
    NUM_CLASSES: 81
    NUM_CONVS: 4
    OCTAVE: 2.0
    PRE_NMS_TOP_N: 1000
    PRIOR_PROB: 0.01
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: 0
    USE_C5: true
  RETINANET_ON: false
  ROI_ATTRIBUTE_HEAD:
    ATTRIBUTE_BGFG_RATIO: 3
    ATTRIBUTE_BGFG_SAMPLE: true
    ATTRIBUTE_LOSS_WEIGHT: 0.1
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    MAX_ATTRIBUTES: 10
    NUM_ATTRIBUTES: 201
    POS_WEIGHT: 5.0
    PREDICTOR: FPNPredictor
    SHARE_BOX_FEATURE_EXTRACTOR: true
    USE_BINARY_LOSS: true
  ROI_BOX_HEAD:
    CONV_HEAD_DIM: 256
    DILATION: 1
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    MLP_HEAD_DIM: 4096
    NUM_CLASSES: 151
    NUM_STACKED_CONVS: 4
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES:
    - 0.25
    - 0.125
    - 0.0625
    - 0.03125
    PREDICTOR: FPNPredictor
    USE_GN: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_WEIGHTS:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
    BG_IOU_THRESHOLD: 0.3
    DETECTIONS_PER_IMG: 40
    FG_IOU_THRESHOLD: 0.5
    NMS: 0.3
    NMS_FILTER_DUPLICATES: true
    POSITIVE_FRACTION: 0.5
    POST_NMS_PER_CLS_TOPN: 300
    SCORE_THRESH: 0.01
  ROI_MASK_HEAD:
    CONV_LAYERS:
    - 256
    - 256
    - 256
    - 256
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    MLP_HEAD_DIM: 1024
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES:
    - 0.0625
    POSTPROCESS_MASKS: false
    POSTPROCESS_MASKS_THRESHOLD: 0.5
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: true
    USE_GN: false
  ROI_RELATION_HEAD:
    ADD_GTBOX_TO_PROPOSAL_IN_TRAIN: true
    BATCH_SIZE_PER_IMAGE: 1024
    CAUSAL:
      CONTEXT_LAYER: motifs
      EFFECT_ANALYSIS: false
      EFFECT_TYPE: none
      FUSION_TYPE: sum
      SEPARATE_SPATIAL: false
    USE_UNION_FEATURES: true
    CLASSIFIER: linear
    CONTEXT_DROPOUT_RATE: 0.2
    CONTEXT_HIDDEN_DIM: 512
    CONTEXT_OBJ_LAYER: 1
    CONTEXT_POOLING_DIM: 4096
    CONTEXT_REL_LAYER: 1
    EMBED_DIM: 200
    FEATURE_EXTRACTOR: RelationFeatureExtractor
    LABEL_SMOOTHING_LOSS: false
    NUM_CLASSES: 51
    NUM_SAMPLE_PER_GT_REL: 4
    POOLING_ALL_LEVELS: true
    POSITIVE_FRACTION: 0.25
    PREDICTOR: MotifPredictor
    PREDICT_USE_VISION: true
    REQUIRE_BOX_OVERLAP: false
    TRANSFORMER:
      DROPOUT_RATE: 0.1
      INNER_DIM: 2048
      KEY_DIM: 64
      NUM_HEAD: 8
      OBJ_LAYER: 4
      REL_LAYER: 2
      VAL_DIM: 64
    USE_FREQUENCY_BIAS: true
    USE_GT_BOX: false
    USE_GT_OBJECT_LABEL: false
  RPN:
    ANCHOR_SIZES:
    - 32
    - 64
    - 128
    - 256
    - 512
    ANCHOR_STRIDE:
    - 4
    - 8
    - 16
    - 32
    - 64
    ASPECT_RATIOS:
    - 0.23232838
    - 0.63365731
    - 1.28478321
    - 3.15089189
    BATCH_SIZE_PER_IMAGE: 256
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FPN_POST_NMS_PER_BATCH: false
    FPN_POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 1000
    MIN_SIZE: 0
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 1000
    PRE_NMS_TOP_N_TEST: 6000
    PRE_NMS_TOP_N_TRAIN: 6000
    RPN_HEAD: SingleConvRPNHead
    RPN_MID_CHANNEL: 256
    STRADDLE_THRESH: 0
    USE_FPN: true
  RPN_ONLY: false
  VGG:
    VGG16_OUT_CHANNELS: 512
  WEIGHT: catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d
  YOLO:
    IMG_SIZE: 640
    OUT_CHANNELS: 256
    SIZE: yolov8l
    WEIGHTS: ''
OUTPUT_DIR: ./output/relation_baseline/motifs
PATHS_CATALOG: sgg_benchmark/config/paths_catalog.py
PATHS_DATA: /home/maelic/Documents/Datasets/VG/
SOLVER:
  BASE_LR: 0.0025
  BIAS_LR_FACTOR: 1
  CHECKPOINT_PERIOD: 2000
  CLIP_NORM: 5.0
  GAMMA: 0.1
  GRAD_NORM_CLIP: 5.0
  IMS_PER_BATCH: 4
  MAX_EPOCH: 100
  MAX_ITER: 900000
  MOMENTUM: 0.9
  OPTIMIZER: SGD
  PRE_VAL: false
  PRINT_GRAD_FREQ: 4000
  SCHEDULE:
    COOLDOWN: 0
    FACTOR: 0.1
    MAX_DECAY_STEP: 3
    PATIENCE: 2
    THRESHOLD: 0.001
    TYPE: WarmupReduceLROnPlateau
  STEPS:
  - 45000
  - 60000
  TO_VAL: true
  UPDATE_SCHEDULE_DURING_LOAD: false
  VAL_PERIOD: 2000
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  ALLOW_LOAD_FROM_CACHE: false
  BBOX_AUG:
    ENABLED: false
    H_FLIP: false
    MAX_SIZE: 4000
    SCALES: []
    SCALE_H_FLIP: false
  CUSTUM_EVAL: false
  CUSTUM_PATH: .
  DETECTIONS_PER_IMG: 100
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 1
  INFORMATIVE: false
  RELATION:
    IOU_THRESHOLD: 0.5
    LATER_NMS_PREDICTION_THRES: 0.5
    MULTIPLE_PREDS: false
    REQUIRE_OVERLAP: false
    SYNC_GATHER: true
  SAVE_PROPOSALS: false
